service: serveress-api-palindrome-date
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-offline-watcher

package:
  individually: true

custom:
  serverless-offline-watcher:
    - path: src/functions/**.ts
      command: echo "Files changed!"

  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    platform: node
    packager: npm

functions:
  check-next-paindrome-date:
    handler: lambdas/check-next-palindrome-date.handler
    events:
      - http:
          path: check-next-paindrome-date/{year}/{month}/{day}
          method: GET

  hello:
    handler: lambdas/hello.handler
    events:
     - http:
        path: hello
        method: GET